### ISSUE TITLE
Cannot add people over cafeteria occupancy

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#157]
Reproduction:
1. Create cafeteria, set capacity to 1 and occupancy to 1.
2. Create camera for this cafeteria
3. Go to CameraEvents, try to add event `person_entered` as this camera.

Request ends with HTTP500. This prevents adding visitors over capacity.

Trace:
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/api/cameraevent/add/

Django Version: 3.0.6
Python Version: 3.7.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'drf_yasg',
 'admin.apps.AdminConfig',
 'home.apps.HomeConfig',
 'api.apps.ApiConfig']
Installed Middleware:
['whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware']



Traceback (most recent call last):
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/kantoniak/.local/share/virtualenvs/server-3TJ96kvy/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/mnt/e/Projekty/2019l-io/django-server/server/api/models.py", line 63, in save
    self.update_cafeteria_occupancy()
  File "/mnt/e/Projekty/2019l-io/django-server/server/api/models.py", line 79, in update_cafeteria_occupancy
    raise ValueError('Invalid CameraEvent fields specification')

Exception Type: ValueError at /admin/api/cameraevent/add/
Exception Value: Invalid CameraEvent fields specification
```

**Comment by avan1235** [comment]
It's intentionally checked not to get more people than the specfied capacity. Now when I think of it, it may cause some issues. Will fix this soon
